name: Run API Tests

on:
  push:
    branches: [main]


job:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: клонируем репоризиторий
        uses: actions/checkout@v3

      - name: устанавливаем python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: зависимости
        run:
          pip install -r requirements.txt

      - name: запускаем тесты
        run: pytest